# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.6
default_acceleration_scaling_factor: 0.6

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# As MoveIt! does not support jerk limits, the acceleration limits provided here are the highest values that guarantee
# that no jerk limits will be violated. More precisely, applying Euler differentiation in the worst case (from min accel
# to max accel in 1 ms) the acceleration limits are the ones that satisfy
# max_jerk = (max_acceleration - min_acceleration) / 0.001

joint_limits:
  panda_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  panda_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  panda_joint1:
    min_position: -2.8104 # -0.5% on both directions, total of 1% cut off # max:-2.897 - original
    max_position:  2.8104 # max:2.897
    has_velocity_limits: true
    max_velocity: 1.2 #0.6  # 2.1750
    has_acceleration_limits: true
    max_acceleration: 3.75
  panda_joint2:
    min_position: -1.7099 # max-1% max:-1.763
    max_position:  1.7099 # max-1% max:1.763
    has_velocity_limits: true
    max_velocity: 1.2 #0.6 #2.1750
    has_acceleration_limits: true
    max_acceleration: 1.875
  panda_joint3:
    min_position: -2.8104 # max -1%, max: -2.897
    max_position:  2.8104 # max-1% max:2.897
    has_velocity_limits: true
    max_velocity: 1.2 #0.6 #2.1750
    has_acceleration_limits: true
    max_acceleration: 2.5
  panda_joint4:
    min_position: -3.0268 # max-1% max:-3.072
    max_position: -0.0248 # max-1% max:-0.07
    has_velocity_limits: true
    max_velocity: 1.2 #0.6 #2.1750
    has_acceleration_limits: true
    max_acceleration: 3.125
  panda_joint5:
    min_position: -2.8104 # max-1% max:-2.897
    max_position:  2.8104 # max-1% max:2.897
    has_velocity_limits: true
    max_velocity: 1.2 #0.6 #2.6100
    has_acceleration_limits: true
    max_acceleration: 3.75
  panda_joint6:
    min_position: 0.0039 # max-1% max:-0.017
    max_position: 3.6960 # max-1% max:3.752
    has_velocity_limits: true
    max_velocity: 1.2 #0.6 #2.6100
    has_acceleration_limits: true
    max_acceleration: 5
  panda_joint7:
    min_position: -2.8104 # max-1% max:-2.897
    max_position:  2.8104 # max-1% max:2.897
    has_velocity_limits: true
    max_velocity: 1.2 #0.6 #2.6100
    has_acceleration_limits: true
    max_acceleration: 5

